import { NextResponse } from 'next/server';
import { requireRole, toErrorResponse } from '@/lib/auth/account';

// POST /api/ai/enhance-image
// Calls Imagen or Hugging Face to generate/enhance listing images
export async function POST(request: Request) {
  try {
    const ctx = await requireRole('agent'); // Require agent role or above
    const accountId = ctx.accountId;
    const supabase = ctx.supabase;

    // Fetch the showcase settings to check the preferred provider
    const { data: settings } = await supabase
      .from('showcase_settings')
      .select('flyer_ai_provider')
      .eq('account_id', accountId)
      .maybeSingle();

    const provider = settings?.flyer_ai_provider || 'huggingface';

    const body = await request.json().catch(() => null);
    if (!body || !body.prompt) {
      return NextResponse.json({ error: 'Prompt is required' }, { status: 400 });
    }

    const { prompt, aspectRatio = '1:1', image } = body;

    if (provider === 'google') {
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        return NextResponse.json(
          { error: 'GEMINI_API_KEY is not configured on the server.' },
          { status: 500 }
        );
      }

      // Use Google AI Studio Imagen 4 predict URL format
      const url = `https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-generate-001:predict?key=${apiKey}`;

      const payload = {
        instances: [
          {
            prompt: prompt,
          },
        ],
        parameters: {
          sampleCount: 1,
          aspectRatio: aspectRatio,
          outputMimeType: 'image/jpeg',
        },
      };

      console.log(`[Imagen AI] Requesting generation with prompt: "${prompt}"`);

      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        const errMessage = errorData.error?.message || `Imagen API error: ${response.statusText}`;
        console.error('[Imagen AI] API call failed:', errMessage);
        return NextResponse.json({ error: errMessage }, { status: response.status });
      }

      const data = await response.json();
      const base64Bytes = data.predictions?.[0]?.bytesBase64Encoded;
      if (!base64Bytes) {
        console.error('[Imagen AI] No predictions or image bytes found in response:', data);
        return NextResponse.json({ error: 'No image was generated by the model.' }, { status: 500 });
      }

      return NextResponse.json({
        image: `data:image/jpeg;base64,${base64Bytes}`,
      });
    } else {
      // HUGGING FACE STABLE DIFFUSION (Free option)
      const hfToken = process.env.HF_ACCESS_TOKEN;
      if (!hfToken) {
        return NextResponse.json(
          { error: 'HF_ACCESS_TOKEN is not configured on the server. Please add a free token from huggingface.co to your settings (.env.local).' },
          { status: 400 }
        );
      }

      console.log(`[HuggingFace AI] Requesting generation with prompt: "${prompt}"`);

      // Use FLUX.1-schnell as it is fully supported by Hugging Face's serverless Inference API (hf-inference)
      let url = 'https://router.huggingface.co/hf-inference/models/black-forest-labs/FLUX.1-schnell';
      let payload: Record<string, unknown> = { inputs: prompt };

      if (image) {
        console.log('[HuggingFace AI] Note: Image-to-image refinement is not supported by free serverless provider. Falling back to text-to-image using FLUX.1-schnell.');
      }

      const response = await fetch(url, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${hfToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        const errorText = await response.text().catch(() => '');
        let errMessage = `Hugging Face API error: ${response.statusText}`;
        try {
          const errorData = JSON.parse(errorText);
          errMessage = errorData.error || errMessage;
          if (response.status === 503 && errorData.estimated_time) {
            return NextResponse.json({
              error: `Hugging Face AI model is warming up. Please try again in ${Math.round(errorData.estimated_time)} seconds.`
            }, { status: 503 });
          }
        } catch {
          if (errorText) errMessage = errorText;
        }
        console.error('[HuggingFace AI] API call failed:', errMessage);
        return NextResponse.json({ error: errMessage }, { status: response.status });
      }

      const buffer = await response.arrayBuffer();
      const base64Bytes = Buffer.from(buffer).toString('base64');

      return NextResponse.json({
        image: `data:image/jpeg;base64,${base64Bytes}`,
      });
    }
  } catch (err: unknown) {
    console.error('[AI Enhance] Exception:', err);
    return toErrorResponse(err);
  }
}
