import { NextResponse } from 'next/server';
import { requireRole, toErrorResponse } from '@/lib/auth/account';

// POST /api/ai/enhance-image
// Calls Imagen 3 to generate/enhance listing images
export async function POST(request: Request) {
  try {
    await requireRole('agent'); // Require agent role or above
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: 'GEMINI_API_KEY is not configured on the server.' },
        { status: 500 }
      );
    }

    const body = await request.json().catch(() => null);
    if (!body || !body.prompt) {
      return NextResponse.json({ error: 'Prompt is required' }, { status: 400 });
    }

    const { prompt, aspectRatio = '1:1' } = body;

    // Use Google AI Studio Imagen 3 predict URL format
    const url = `https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-002:predict?key=${apiKey}`;

    const payload = {
      instances: [
        {
          prompt: prompt,
        },
      ],
      parameters: {
        sampleCount: 1,
        aspectRatio: aspectRatio,
        outputMimeType: 'image/jpeg',
      },
    };

    console.log(`[Imagen AI] Requesting generation with prompt: "${prompt}", Aspect Ratio: ${aspectRatio}`);

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      const errMessage = errorData.error?.message || `Imagen API error: ${response.statusText}`;
      console.error('[Imagen AI] API call failed:', errMessage);
      return NextResponse.json({ error: errMessage }, { status: response.status });
    }

    const data = await response.json();
    const base64Bytes = data.predictions?.[0]?.bytesBase64Encoded;
    if (!base64Bytes) {
      console.error('[Imagen AI] No predictions or image bytes found in response:', data);
      return NextResponse.json({ error: 'No image was generated by the model.' }, { status: 500 });
    }

    return NextResponse.json({
      image: `data:image/jpeg;base64,${base64Bytes}`,
    });
  } catch (err: unknown) {
    console.error('[Imagen AI] Exception:', err);
    return toErrorResponse(err);
  }
}
